name: DeplotToS3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      -"dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run build
    - run: npm test
